name: Aviatrix Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Apply terraform
      run: |
        curl -XPOST ${{ secrets.WORKFLOW_ENDPOINT }} \
          -H 'Content-Type: application/json' \
          -d '{"action": "run_workflow", "dag_id": "github_apply_terraform", "payload": {"conf": {"repo_url": "https://github.com/nmanville/workflow_test.git"}}}'
