name: Aviatrix Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install Requirements
      run: |
        python -m pip install --upgrade --disable-pip-version-check pip
        python -m pip install --upgrade requests

    - uses: jannekem/run-python-script-action@v1
      with:
        script: |
          import requests
          import json

          endpoint = ${{ secrets.WORKFLOW_ENDPOINT }}
          headers = {
              "accept": "application/json",
              "Content-Type": "application/json",
          }
          payload = {"repository": ${{ github.repository }} }
          req = requests.post(
              f"{endpoint}/update_tf",
              headers=headers,
              data=json.dumps(payload),
          )
          print(req.json())
